services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80/tcp"
        environment:
            TZ: 'America/Managua'
            WEBPASSWORD: '%XTWodu3j5YaTvfB'
            # Volumes store your data between container upgrades
        volumes:
            - './etc-pihole:/etc/pihole'
            - './etc-dnsmasq.d:/etc/dnsmasq.d'
        restart: unless-stopped

    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - JELLYFIN_PublishedServerUrl=192.168.1.8 #optional
        volumes:
            - /mnt/USB:/config
            - /mnt/USB/tvseries:/data/tvshows
            - /mnt/USB/movies:/data/movies
        ports:
            - 8096:8096
            - 8920:8920 #optional
            - 7359:7359/udp #optional
            - 1900:1900/udp #optional
        restart: unless-stopped
